### ISSUE TITLE
need publish permission

### ISSUE THREAD

**Issue by phated** [gulpjs/hacker#2]
cc @tkellen

**Comment by tkellen** [comment]
All set. I'd close this issue but it appears I don't have the permission to do so? Any chance you can rectify that across the board for repos in this org @phated?

**Comment by phated** [comment]
Yep! Trying to churn through these as fast as I can. Cheers and happy holidays.

**Comment by fifitie** [comment]
sudo npm install -g camera.ui@latest https://instagram.com/nidablnt?utm_medium=copy_link
